### ISSUE TITLE
How sibyl can identify a function ?

### ISSUE THREAD

**Issue by hackmoonlight** [cea-sec/Sibyl#15]
I am interested to work with siby , the most interesting thing is that sibyl can detect  the name of the function (strsep , strchr , strncmp ....)  , how sibyl can do this ? it has a database of templates and it is just comparing ? 

```
Python>identify_all("x86_32", "ABIStdCall_x86_32")
Launch identification on 3056 function(s)
Current: 65.45% (sub_0x80b6d8c)| Estimated time remaining: 49.80s
0x08057258 : strncmp
0x080576ac : strsep
0x08057b48 : strcmp,strncmp
0x080571cc : strchr
0x08057244 : strlen
0x08057704 : strspn
0x08057b30 : strtok
```

**Comment by commial** [comment]
Well, it is probably not clear enough in the README.
Sibyl has a database of signatures (under its `test` directory), which basically describe, for each known function, how to set up an initial state and how to check a resulting state.

Then, according to the specified architecture and ABI, Sibyl will set up the environment (allocate needed memory, set strings, registers and so on), and then run the candidate function in an emulated environment.

If the function runs through the end, the resulting state is checked: the returned value according to the ABI, the state of the memory, ...
If the resultating state match the expected one, Sibyl will say "it looks like a bird, it's probably a bird" and will consider that it found the corresponding name.

Then, there are a few additional mechanism, for instance the possibility to run several tests before returning an answer. There are also a few optimisation to avoid loosing to much time on different tests.

Hope I've clarify some points.
