### ISSUE TITLE
error while using sibyl

### ISSUE THREAD

**Issue by houjingyi233** [cea-sec/Sibyl#70]
root@ubuntu:/usr/local/bin# sibyl
Usage: /usr/local/bin/sibyl [action]

Actions:
Traceback (most recent call last):
  File "/usr/local/bin/sibyl", line 33, in <module>
    key=lambda action: action._name_)]
  File "/usr/local/bin/sibyl", line 33, in <lambda>
    key=lambda action: action._name_)]
AttributeError: 'ActionDesc' object has no attribute '_name_'

On latest ubuntu 17.04 x86 and latest miasm

**Comment by commial** [comment]
Hi @houjingyi233,

It does work for me, on nearly the same configuration.
Can you do the following:
```Python
$ python(2) -i sibyl
...
Traceback (most recent call last):
File "/usr/local/bin/sibyl", line 33, in
key=lambda action: action.name)]
File "/usr/local/bin/sibyl", line 33, in
key=lambda action: action.name)]
AttributeError: 'ActionDesc' object has no attribute 'name'
>>> from pdb import pm
>>> pm()
(pdb) l
(pdb) print repr(action)
(pdb) up
(pdb) print ACTIONS
```
And print back the result?

Thanks in advance!
