### ISSUE TITLE
Binary Ninja plugin

### ISSUE THREAD

**Issue by kenoph** [cea-sec/Sibyl#71]
Hi,

I wrote a simple Binja plugin for using Sibyl.
As of now I'm running it in a single thread but maybe I'll go the way of your plugin and use `subprocess`.

Anyway, if you can add a link to it in your repo it would be very nice :)

https://github.com/kenoph/binja_sibyl

(The reason why I did not add it as an ext is that binja requires a `plugin.json` file in the root of the repo, along with `__init__.py`... I don't want to pollute your repo)

EDIT: Oh yeah, forgot to thank you for the tool. When I read what it does I had an "aha" moment.

**Comment by commial** [comment]
Hi @kenoph,

Thanks for you interest in Sibyl!
I've add a link in the README to your binary ninja stub (see #72).

What you can do for your stub is, as you said, call `sibyl` as an external process and get a JSON output to parse. This is how it is done in the IDA stub, and as a bonus, it also allow sibyl to run on an external server / linux VM (for Windows users...)

**Comment by kenoph** [comment]
Appreciate it ;) I read the IDA plugin source code, but wanted to implement a "clean" version before going the subprocess route (for whatever reason).
