### ISSUE TITLE
PYCParser requirement issue

### ISSUE THREAD

**Issue by guedou** [cea-sec/Sibyl#74]
Calling `sibyl find` produces an error if pycparser is not installed. Do you think that it could be useful to add a `requirements,txt` that will install it?

**Comment by commial** [comment]
Hey, thanks for reporting it.
It should not be a mandatory dependency. Actually, the code should already manage this case (`sibyl/commons.py`).
I'll try to reproduce and investigate

**Comment by guedou** [comment]
Here are the steps to reproduce:
```
$ git clone https://github.com/cea-sec/Sibyl
$ cd Sibyl
$ virtualenv -p python2 ve_sibyl
$ source ve_sibyl/bin/activate
$ pip install git+https://github.com/cea-sec/miasm/
$ python setup.py install
$ sibyl find
[..]
ImportError: No module named pycparser
```
