### ISSUE TITLE
Don't support UC_MOD_THUMB

### ISSUE THREAD

**Issue by Vitaly-Protasov** [cea-sec/Sibyl#90]
Hi, am i right that sibyl can't work with emulation at UC_MOD_THUMB (unicorn thumb mode didn't use) ?

Because in "qemu.py" is using only:
`uc_mode = unicorn.UC_MODE_ARM + unicorn.UC_MODE_LITTLE_ENDIAN`

**Comment by Vitaly-Protasov** [comment]
#fixed will add changes later if it need

**Comment by Vitaly-Protasov** [comment]
#91

**Comment by commial** [comment]
Fixed by #92
