### ISSUE TITLE
ImportError: No module named core.utils

### ISSUE THREAD

**Issue by plowsec** [cea-sec/Sibyl#95]
Hi,
Thank you for your work, this looks amazing :-)
Upon installing Sibyl, I encountered some install errors. The first one it that the python cli tool imports miasm2, which appear to have be renamed to "miasm".

I replaced every occurrence to miasm2 accordingly in Sibyl. And then I have a weird bug:
```
python2 run_all_tests.py   
Traceback (most recent call last):
  File "run_all_tests.py", line 6, in <module>
    from learn import test_learn
  File "/home/vladimir/tools/Sibyl/test/learn/__init__.py", line 1, in <module>
    from .run_tests import test_learn
  File "/home/vladimir/tools/Sibyl/test/learn/run_tests.py", line 11, in <module>
    from sibyl.testlauncher import TestLauncher
  File "/usr/lib/python2.7/site-packages/sibyl/testlauncher.py", line 26, in <module>
    from sibyl.engine import QEMUEngine, MiasmEngine
  File "/usr/lib/python2.7/site-packages/sibyl/engine/__init__.py", line 3, in <module>
    from sibyl.engine.qemu import QEMUEngine
  File "/usr/lib/python2.7/site-packages/sibyl/engine/qemu.py", line 1, in <module>
    from miasm.core.utils import pck32, pck64
ImportError: No module named core.utils
```
However:
```
python2                                           :(
Python 2.7.16 (default, Mar 11 2019, 18:59:25) 
[GCC 8.2.1 20181127] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from miasm.core.utils import pck32, pck64
>>> 
```
So, what am I doing wrong? Because I have no idea what the heck is going on.

**Comment by p-l-** [comment]
Hi,

Did you get (and install) the correct version of Miasm? As stated in the readme, "Sibyl requires at least Miasm2 version v0.1.1".

**Comment by plowsec** [comment]
Yes of course :)
In fact, I use the version on miasm' master branch.

```
python2
Python 2.7.16 (default, Mar 11 2019, 18:59:25) 
[GCC 8.2.1 20181127] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import miasm
>>> miasm.VERSION
u'0.1.1.dev118'
>>> 
```

**Comment by p-l-** [comment]
I think you need 0.1.1 (with the corresponding elfesteem...), not 0.1.1.dev*.

**Comment by plowsec** [comment]
How can this be related? :o
Anyway, I tried with sources from https://github.com/cea-sec/miasm/archive/v0.1.1.zip, repeated the install process and the Sibyl tests, same result.

The import of miasm works fine in an python interpreter, so this can't be a miasm installation issue, am I right?

**Comment by p-l-** [comment]
I don't know what the problem is.

Did you change the `miasm` import back to `miasm2`? (if not, chances are you are still using the dev version).

**Comment by p-l-** [comment]
Actually, I think have identified the issue: some files in Sibyl are called `miasm.py`, and Python wants to import objects from there.

Using the correct (0.1.1) version of Miasm and leaving Sibyl code unchanged (with `miasm2` imports) should work.

BTW @commial you may have to rename those files when Sibyl supports the future versions of Miasm.

**Comment by plowsec** [comment]
Oh right that was it, thank you ! <3
