### ISSUE TITLE
ImportError: No module named miasm2.analysis.machine

### ISSUE THREAD

**Issue by BitsOfBinary** [cea-sec/Sibyl#97]
After installing the latest version of miasm, it seems to break sibyl based off how it tries to import miasm2 when that no longer appears to be a thing (https://github.com/cea-sec/miasm/commit/944806c506446c918eb74c17a605f5f56d4b75e0).

I'm not sure if I'm doing something wrong, perhaps changing all "miasm2" to "miasm" will help?

**Comment by commial** [comment]
Hello,

As stated in #95 and #96 , Sibyl relies on the latest Miasm *stable* version, which is the `v0.1.1`.
Having Miasm installed in this version should fixed the problem.

The support for the more recent Miasm namespace will come with the release of the new Miasm version.

**Comment by BitsOfBinary** [comment]
Thank you! I should have seen these other issues, but cheers for answering thoroughly anyhow :)
